// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB62AeSu3-GH9T0jzYO93WQeP4DVkmXQaE',
    appId: '1:65738840441:web:b3b6d5eba2076fe2ecf7a8',
    messagingSenderId: '65738840441',
    projectId: 'flutternovel',
    authDomain: 'flutternovel.firebaseapp.com',
    storageBucket: 'flutternovel.appspot.com',
    measurementId: 'G-EYPKE04CR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwPXlhaLy30HIvKTkcGIPnQlt3rQfp_U',
    appId: '1:65738840441:android:089cbe86204c05a1ecf7a8',
    messagingSenderId: '65738840441',
    projectId: 'flutternovel',
    storageBucket: 'flutternovel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWsMGUifAXKJvJMLDZ5bj3OAJ72d8esg',
    appId: '1:65738840441:ios:768094c7c3fcdbb3ecf7a8',
    messagingSenderId: '65738840441',
    projectId: 'flutternovel',
    storageBucket: 'flutternovel.appspot.com',
    iosBundleId: 'com.example.flutterNovel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWsMGUifAXKJvJMLDZ5bj3OAJ72d8esg',
    appId: '1:65738840441:ios:0dbf603c12c6b084ecf7a8',
    messagingSenderId: '65738840441',
    projectId: 'flutternovel',
    storageBucket: 'flutternovel.appspot.com',
    iosBundleId: 'com.example.flutterNovel.RunnerTests',
  );
}
